title: "Le Club"
tagline: "Workshops"
permalink: /:year/:month/:title/
future: true

tagline : "Learn. Code. Create."
description: "Le Club delivers training, workshops and support for creative projects."

keywords: ['creative coding', 'data visualization', 'installation', 'network analysis']

# sns
github: leclub
email: "contact@leclub.io"
twitter: __leClub

# build settings
encoding: utf-8
exclude: [README.md, LICENSE, CNAME]

sass:
  sass_dir: scss
