title: "Le Club"
tagline : "Learn. Code. Create."
description: "Le Club delivers training, workshops and support for creative projects."
keywords: ['creative coding', 'data visualization', 'installation', 'network analysis']

# sns
github: leclub
email: "contact@leclub.io"
twitter: __leClub

url: http://leclub.io

# build settings
permalink: /:year/:month/:title/
future: true
encoding: utf-8

exclude: [README.md, LICENSE, CNAME, start.bat]
include: [.htaccess]
show_drafts: false

sass:
  sass_dir: scss
